#!/bin/sh

# (c) 2025 by Harald Weidner
# License: MIT
#
# Checkmk local check
# displays information about pending Alpine (APK) package updates
#
# example output:
#
# 2 "APK updates" updates=5 There are 5 updates available.

CHECK='"APK updates"'

if type apk >/dev/null 2>&1 ; then
  apk update > /dev/null 2>&1
  updates=$(apk list -u | cut -d' ' -f1 | tr '\n' ' ')
  num_updates=$(echo $updates | wc -w)
  if [ -n "$updates" ]; then
    echo "2 $CHECK updates=$num_updates $num_updates updates available: $updates"
  else
    echo "0 $CHECK updates=0 No updates available"
  fi
fi

exit 0
